#!/bin/bash

source "vendor/bash-utility/src/format.sh"

# USING ANSI COLORS
BLACK="\e[30m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
PURPLE="\e[35m"
CYAN="\e[36m"
WHITE="\e[37m"


# The actual script start from here:
echo "${RED}"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
echo "${GREEN}"
figlet -tc H O S S E I N
figlet -tc M O U S A V I
echo "${GREEN}"
echo "${RED}"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -

sleep 0.5s
echo "${CYAN}"
#figlet -tc Software
sleep 0.5s 
#figlet -tc Developer
echo "${YELLOW}"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
sleep 0.5s
echo "I have worked with JavaScript"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
format::text_center "This text is in centre of the terminal."

